<?php
/**
 * @file
 * vcard_field_history.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function vcard_field_history_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'user-user-field_history'.
  $field_instances['user-user-field_history'] = array(
    'bundle' => 'user',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'bypass_access' => FALSE,
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'user',
    'field_name' => 'field_history',
    'label' => 'History',
    'required' => 0,
    'settings' => array(
      'user_register_form' => 0,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 10,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('History');

  return $field_instances;
}
