<?php
/**
 * @file
 * Module's main file.
 */

$path = drupal_get_path('module', 'vcard_main');
require_once $path . '/my_vcards.inc';
require_once $path . '/groups.inc';
require_once $path . '/history.inc';
require_once $path . '/settings.inc';
require_once $path . '/user.inc';

/**
 * Implements hook_menu().
 */
function vcard_main_menu() {
  $items = [];

  $items['my-vcards'] = [
    'title' => 'My VCards',
    'title callback' => 'vcard_main_my_vcards_title',
    'menu_name' => 'main-menu',
    'page callback' => '_entity_page',
    'page arguments' => ['vcard'],
    'access callback' => TRUE,
  ];
  $items['my-vcards/add'] = [
    'title' => 'Add VCard',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_my_vcard_form'],
    'access arguments' => ['create vcard content'],
    'type' => MENU_CALLBACK,
  ];
  $items['ajax/vcard/%/view'] = [
    'page callback' => 'vcard_main_vcard_view_ajax',
    'page arguments' => [2],
    'type' => MENU_CALLBACK,
    'access arguments' => ['access content'],
    'delivery callback' => 'vcard_main_entity_ajax_callback',
  ];
  $items['my-vcards/%/%'] = [
    'title callback' => 'vcard_main_my_vcard_form_edit_title',
    'title arguments' => [2],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_my_vcard_form', 1, 2],
    'access callback' => 'user_access',
    'access arguments' => ['edit own vcard content'],
    'type' => MENU_CALLBACK,
  ];
  $items['my-vcards/%/remove'] = [
    'title' => 'Remove VCard',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_my_vcard_form_remove', 1],
    'access arguments' => ['delete own vcard content'],
    'type' => MENU_CALLBACK,
  ];
  $items['groups'] = [
    'title' => 'Groups',
    'menu_name' => 'main-menu',
    'page callback' => '_entity_page',
    'page arguments' => ['group'],
    'access arguments' => ['access content'],
  ];
  $items['group/add'] = [
    'title' => 'Add group',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_group_form'],
    'access arguments' => ['create vcard content'],
    'type' => MENU_CALLBACK,
  ];
  $items['group/add/%ctools_js'] = [
    'page callback' => 'vcard_main_group_add_ajax',
    'page arguments' => [2],
    'type' => MENU_CALLBACK,
    'access arguments' => ['access content'],
  ];
  $items['ajax/group/%/view'] = [
    'page callback' => 'vcard_main_group_view_ajax',
    'page arguments' => [2],
    'type' => MENU_CALLBACK,
    'access arguments' => ['access content'],
    'delivery callback' => 'vcard_main_entity_ajax_callback',
  ];
  $items['ajax/group/%/credits'] = [
    'page callback' => 'vcard_main_group_credits_ajax',
    'page arguments' => [2],
    'type' => MENU_CALLBACK,
    'access arguments' => ['access content'],
  ];
  $items['group/edit/%/%ctools_js'] = [
    'page callback' => 'vcard_main_group_edit_ajax',
    'page arguments' => [2, 3],
    'type' => MENU_CALLBACK,
    'access arguments' => ['edit own vcard content'],
  ];
  $items['group/delete/%/%ctools_js'] = [
    'page callback' => 'vcard_main_group_remove_ajax',
    'page arguments' => [2, 3],
    'type' => MENU_CALLBACK,
    'access arguments' => ['delete own vcard content'],
  ];
  $items['history'] = [
    'title' => 'History',
    'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_history_form'],
    'access arguments' => ['access content'],
  ];
  $items['settings'] = [
    'title' => 'Settings',
    'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vcard_main_settings_form'],
    'access arguments' => ['access content'],
  ];
  $items['logout'] = [
    'title' => 'Log Out',
    'menu_name' => 'main-menu',
    'page callback' => 'vcard_main_logout',
    'access arguments' => ['access content'],
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function vcard_main_theme($existing, $type, $theme, $path) {
  $templates = drupal_get_path('theme', 'vcard') . '/templates';
  return [
    'entity_nano_teaser' => [
      'variables' => [
        'entity_type' => NULL,
        'nid' => NULL,
        'logo_uri' => NULL,
        'title' => NULL,
      ],
      'path' => $templates,
      'template' => 'entity-nano-teaser',
    ],
    'vcard_details_view' => [
      'variables' => [
        'node' => NULL,
        'editable' => FALSE,
      ],
      'path' => $templates,
      'template' => 'vcard-details-view',
    ],
    'my_vcard_form' => [
      'render element' => 'form',
      'template' => 'my-vcard-form',
      'path' => $templates,
    ],
    'group_details_view' => [
      'variables' => [
        'group' => NULL,
      ],
      'path' => $templates,
      'template' => 'group-details-view',
    ],
  ];
}

/**
 * Helper function provides two columns on page.
 */
function _entity_page($entity_type = NULL) {
  if (!$entity_type) {
    return FALSE;
  }

  global $user;
  $page = [];

  // Return void for anonymous user.
  // This page will display an authorization form.
  if (!$user->uid) {
    return $page;
  }

  // Left column.
  $page['entity_list_wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['list-wrapper', 'large-4', 'medium-4', 'columns'],
    ],
  ];
  $page['entity_list_wrapper']['nano'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['nano'],
    ],
  ];
  $page['entity_list_wrapper']['nano']['entity_list'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['nano-content'],
    ],
  ];

  //  Right column.
  $page['entity_view_wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['entity-view-wrapper', 'large-8', 'medium-8', 'columns'],
    ],
  ];
  $page['entity_view_wrapper']['nano'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['nano'],
    ],
  ];
  $page['entity_view_wrapper']['nano']['content'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['nano-content'],
    ],
  ];

  $user_wrapper = entity_metadata_wrapper('user', $user);

  switch ($entity_type) {
    case 'vcard' :
      _vcard_attach_page_content($page, $user_wrapper);
      break;

    case 'group':
      _groups_attach_page_content($page, $user_wrapper);
      break;
  }

  $page['#attached'] = [
    'js' => [
      drupal_get_path('theme', 'vcard') . '/js/entity_view_ajax_load.js',
    ],
  ];

  return $page;
}

/**
 * Html deliver for view Entities.
 *
 * @param $page_callback_result
 */
function vcard_main_entity_ajax_callback($page_callback_result) {
  print $page_callback_result;
  drupal_page_footer();
}

/**
 * Helper function save relations to user entity field.
 *
 * @param $field_name
 *  Entity reference field name in user entity.
 * @param $entity_id
 *  For example: VCard node "nid" or Group entity "id".
 */
function _user_entityreference_field_save($field_name, $entity_id) {
  global $user;
  $wrapper = entity_metadata_wrapper('user', $user);

  if (isset($wrapper->{$field_name})) {
    $entity_field = $wrapper->{$field_name}->value();
    $ids = [];
    foreach ($entity_field as $key => $item) {
      // Remove ids of referenced entities that has been deleted.
      if (!$item) {
        unset($wrapper->{$field_name}[$key]);
      }
      else {
        $ids[] = $item->type == 'vcard' ? $item->nid : $item->id;
      }
    }
    // Save if new VCard created.
    if (!in_array($entity_id, $ids)) {
      $wrapper->{$field_name}[] = intval($entity_id);
    }
  }
  else {
    watchdog(
      'error',
      t('Field @field_name does not exists for user.', ['@field_name' => $field_name])
    );
  }
  $wrapper->save();
}

/**
 * Implements hook_block_info().
 */
function vcard_main_block_info() {
  $blocks = [];

  $blocks['groups_toolbar'] = [
    'info' => t('Groups toolbar'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => TRUE,
    'region' => 'header',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'groups',
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function vcard_main_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'groups_toolbar':
      $block['content'] = ' ';
      break;
  }

  return $block;
}

/**
 * Home page title callback.
 */
function vcard_main_my_vcards_title() {
  global $user;

  return $user->uid ? t('My VCards') : t('Authorization');
}

/**
 * Implements hook_field_formatter_info().
 */
function vcard_main_field_formatter_info() {
  return [
    'base64_image' => [
      'label' => t('Base64 image'),
      'description' => t('Render external path to image or base64 text as image.'),
      'field types' => [
        'text_long',
        'blob',
        'blob_long',
      ],
    ],
  ];
}

/**
 * Implements hook_field_formatter_view().
 */
function vcard_main_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = [];

  switch ($display['type']) {
    case 'base64_image':
      foreach ($items as $delta => $item) {
        $element[$delta] = [
          '#markup' => '<img src="' . $item['value'] . '" />',
        ];
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_entity_info_alter().
 */
function vcard_main_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['image'] = [
    'label' => t('Image'),
    'custom settings' => TRUE,
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vcard_main_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  $form['combine']['#attributes'] = ['placeholder' => t('Search')];
  $form['combine']['#title'] = '<i class="material-icons">search</i>';
}

/**
 * Implements hook_form_alter().
 */
function vcard_main_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'vcard_main_my_vcard_form_remove':
    case 'vcard_main_group_remove_form':
      $form['actions']['cancel']['#attributes'] = [
        'class' => 'button',
      ];
      break;
  }
}
