<?php
/**
 * @file
 * Module's main file.
 */

/**
 * Defines site main theme name.
 */
define('VCARD_THEME_NAME', 'vcard');

/**
 * Defines social links names.
 */
define('FACEBOOK', 'Facebook');
define('TWITTER', 'Twitter');
define('GOOGLE_PLUS', 'Google+');
define('LINKEDIN', 'LinkedIn');
define('YOUTUBE', 'YouTube');
define('INSTAGRAM', 'Instagram');
define('VKONTAKTE', 'VKontakte');
define('SKYPE', 'Skype');
define('VIBER', 'Viber');
define('WHATSAPP', 'WhatsApp');
define('TELEGRAM', 'Telegram');
define('MESSENGER', 'Facebook messenger');

/**
 * Implements hook_schema_alter().
 */
function vcard_core_schema_alter(&$schema) {
  $schema['users']['fields']['changed'] = [
    'description' => 'The Unix timestamp when the user was most recently saved.',
    'type' => 'int',
    'not null' => TRUE,
    'default' => 0,
  ];
  $schema['users']['fields']['last_login_token'] = [
    'description' => 'Token generated when user synchronize to server.',
    'type' => 'varchar',
    'length' => 36,
    'not null' => FALSE,
  ];
}

/**
 * Implements hook_user_presave().
 */
function vcard_core_user_presave(&$edit, $account, $category) {
  if (isset($account->is_new) && $account->is_new) {
    // Generate random first login token if user register from site.
    $edit['last_login_token'] = _get_uuid();
  }
  $edit['changed'] = time();
}

/**
 * Implements hook_user_insert().
 */
function vcard_core_user_insert(&$edit, $account, $category) {
  // Create VCard comment and bind to account.
  $comment_entity = entity_create('vcard_comment', [
    'type' => 'vcard_comment',
    'id' => $account->uid,
  ]);
  entity_save('vcard_comment', $comment_entity);

  $wrapper = entity_metadata_wrapper('user', $account->uid);
  // Set name the same as email.
  $wrapper->name->set($edit['mail']);
  // Bind VCard comment entity to account.
  $wrapper->field_vcard_comment->set(intval($comment_entity->id));
  $wrapper->save();
}

/**
 * Implements hook_mail_alter().
 */
function vcard_core_mail_alter(&$message) {
  $message['send'] = FALSE;
}

/**
 * Implements hook_block_info_alter().
 */
function vcard_core_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Configure default blocks.
  $blocks['system']['navigation']['status'] = FALSE;
  $blocks['user']['login']['region'] = 'content';
}
