<?php
/**
 * @file
 * Module's main file.
 */

/**
 * Implements hook_menu().
 */
function custom_menu() {
  $items = [];
  $items['home'] = [
    'type' => MENU_CALLBACK,
    'page callback' => 'custom_home_page',
    'access callback' => TRUE,
  ];

  return $items;
}

/**
 * Home page callback.
 */
function custom_home_page() {
  $page = [];

  return $page;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function custom_form_user_login_block_alter(&$form, &$form_state) {
  $form['name']['#title_display'] = 'invisible';
  $form['name']['#attributes'] = ['placeholder' => t('E-mail')];
  $form['pass']['#title_display'] = 'invisible';
  $form['pass']['#attributes'] = ['placeholder' => t('Password')];
}

/**
 * Implements hook_block_view_alter().
 */
function custom_block_view_alter(&$data, $block) {
  switch ($block->delta) {
    case 'login':
      // Remove unnecessary title.
      unset($data['subject']);
      // Set link after "Log in" button.
      $data['content']['links']['#weight'] = 101;
      // Hide unnecessary links.
      $data['content']['links']['#access'] = FALSE;
      // Set google button on the top of block.
      $data['content']['submit_google']['#weight'] = -1;
      break;
  }
}
